### PR TITLE
added cool native for category, proper blip creation * all hail bdub*

### PR DESCRIPTION
**Pull request by MrNewb**
added cool native for category, proper blip creation * all hail bdub*

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) loaded on normal qb core, it works there and the blip system seems the same here
- Does your code fit the style guidelines? [yes/no] not a clue
- Does your PR fit the contribution guidelines? [yes/no] not a clue

### CODE REVIEW

**Review by ihyajb — APPROVED** [review]
You probably could fix the formatting but, LGTM

**Comment by MrNewb** [comment]
> You probably could fix the formatting but, LGTM

tbh idk why it does that, im very uneducated in visual studio and normally do everything in notepad++. Im in the discord if you have any tips or guidance on visual studio. Id love to learn what extensions work to beautify/turn spaces into tabs

**Review by BerkieBb — APPROVED** [review]

**Review by D4isDAVID — APPROVED** [review]
Looks fine.

**Review by HebiKotei — APPROVED** [review]
Nothing glaringly wrong

**Pull request merged**
